version: '3.4'
services:
  colour_board_base : &colour_board_base
    build: .
    ports:
     - '3000:3000'
    volumes:
      - './src:/code/src'
    environment:
      REDIS_HOST: 'test'

  colour_board:
    container_name: colour_board_web
    <<: *colour_board_base
    build:
      context: .
      target: production

  colour_board_dev:
    container_name: colour_board_web_dev
    <<: *colour_board_base
    build:
      context: .
      target: development

  # testing redis server, not required.
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'