version: '3'
services:
  colour_board:
    container_name: web
    build: .
    ports:
     - "3000:3000"
    volumes:
      - "./src:/code/src"
    environment:
      REDIS_HOST: "test"

  # TODO: use colour_board as base, currently have some duplication
  colour_board_dev:
      container_name: web
      build:
        context: .
        args:
          DEVELOPMENT: "true"
      ports:
       - "3000:3000"
      volumes:
        - "./src:/code/src"
      environment:
        REDIS_HOST: "test"